# Generated by Django 2.1.2 on 2018-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZephyrAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('so2', models.IntegerField(blank=True, null=True)),
                ('no2', models.IntegerField(blank=True, null=True)),
                ('pm2_5', models.IntegerField(blank=True, null=True)),
                ('pm10', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ZephyrAPI',
            },
        ),
    ]
