# Generated by Django 2.1.2 on 2018-10-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zephyr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
