# Generated by Django 2.1.2 on 2018-10-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zephyr', '0002_auto_20181020_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
